### ISSUE TITLE
Cannot run train.py since file missing

### ISSUE THREAD

**Issue by Agnes-L** [zcc1203/KGE-UNIT#2]
I tried to run train.py, but failed with missing res/warm/conve.txt and res/cold/conve.txt. Could you please provide these files? I did not find these files in zenodo, either.

**Comment by shisumengq** [comment]
现在怎么样啦 跑通了嘛

**Comment by dota123-star** [comment]
你好，这个是结果文件，不需要提供，建一个空文件，只是程序里往里面写结果的

**Comment by dota123-star** [comment]
> 现在怎么样啦 跑通了嘛

这个只需要自己新建一个就可以，不需要提高，只是用于记录结果

**Comment by shisumengq** [comment]
> 你好，这个是结果文件，不需要提供，建一个空文件，只是程序里往里面写结果的
感谢您的指导
Traceback (most recent call last):
  File "train.py", line 483, in <module>
    main()
  File "train.py", line 435, in main
    fp = open(res_path,'w')
FileNotFoundError: [Errno 2] No such file or directory: 'res/warm/conve.txt'
这个是我的报错信息 我不知道 该新建一个什么文件夹  麻烦您帮我看看这个该怎么办

**Comment by shisumengq** [comment]
> 你好，这个是结果文件，不需要提供，建一个空文件，只是程序里往里面写结果的

Traceback (most recent call last):
  File "train.py", line 483, in <module>
    main()
  File "train.py", line 435, in main
    fp = open(res_path,'w')
FileNotFoundError: [Errno 2] No such file or directory: 'res/warm/conve.txt'
这个该建什么文件夹呀 求助 求求

**Comment by zcc1203** [comment]
> > 你好，这个是结果文件，不需要提供，建一个空文件，只是程序里往里面写结果的
> 
> Traceback (most recent call last): File "train.py", line 483, in main() File "train.py", line 435, in main fp = open(res_path,'w') FileNotFoundError: [Errno 2] No such file or directory: 'res/warm/conve.txt' 这个该建什么文件夹呀 求助 求求

简单的来说，就是程序根目录下面res文件夹下面建个warm文件夹路径，就可以了。代码的话就是在fp=open(res_path,'w')前面加上if not os.path.exists(folder_path):  
    os.makedirs(folder_path)
这里folder_path=‘res/warm/‘

**Comment by shisumengq** [comment]
太感谢您了！！！我试试





------------------ Original ------------------
From: zcc1203 ***@***.***&gt;
Date: Tue,Jan 28,2025 3:35 PM
To: zcc1203/KGE-UNIT ***@***.***&gt;
Cc: shisumengq ***@***.***&gt;, Comment ***@***.***&gt;
Subject: Re: [zcc1203/KGE-UNIT] Cannot run train.py since file missing (Issue#2)





   
你好，这个是结果文件，不需要提供，建一个空文件，只是程序里往里面写结果的
  
Traceback (most recent call last): File "train.py", line 483, in main() File "train.py", line 435, in main fp = open(res_path,'w') FileNotFoundError: [Errno 2] No such file or directory: 'res/warm/conve.txt' 这个该建什么文件夹呀 求助 求求
  
简单的来说，就是程序根目录下面res文件夹下面建个warm文件夹路径，就可以了。代码的话就是在fp=open(res_path,'w')前面加上if not os.path.exists(folder_path):
 os.makedirs(folder_path)
 这里folder_path=‘res/warm/‘
